# Generated by Django 2.2.24 on 2021-06-04 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('month', models.PositiveSmallIntegerField(choices=[(0, 'January'), (1, 'February'), (2, 'March'), (3, 'April'), (4, 'May'), (5, 'June'), (6, 'July'), (7, 'August'), (8, 'September'), (9, 'October'), (10, 'November'), (11, 'December')])),
                ('year', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='portfolio/static/portfolio/img/project_images/')),
                ('summary', models.CharField(max_length=70)),
                ('details', models.TextField()),
                ('show', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-year', '-month', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rank', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'skill category',
                'verbose_name_plural': 'skill categories',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('proficiency', models.PositiveSmallIntegerField(help_text='0-100')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.SkillCategory')),
            ],
            options={
                'ordering': ['category', '-proficiency', 'name'],
            },
        ),
    ]
